const BASE = 'https://sulforwanda.com/wp-content/uploads';

export const SULFO_PRODUCTS = [
  // ── LAUNDRY SOAP ───────────────────────────────────────────────
  {
    name: 'Safari Blue Laundry Soap 600g',
    brand: 'Safari', category: 'Laundry Soap', subcategory: 'Bar Soap',
    price: 1200, stock: 250, weight: '600g',
    description: 'Powerful Safari Blue laundry soap for brilliant cleaning results. Ideal for hand washing and machine use. Trusted by Rwandan families for decades.',
    features: ['Powerful stain removal','Gentle on fabrics','Long-lasting freshness','Made in Rwanda'],
    image: `${BASE}/2024/05/Safari-blue-ft.jpg`,
    images: [`${BASE}/2024/05/Safari-blue-ft.jpg`, `${BASE}/2023/12/IMG001.jpg`],
    tag: 'bestseller',
  },
  {
    name: 'Safari White Laundry Soap 600g',
    brand: 'Safari', category: 'Laundry Soap', subcategory: 'Bar Soap',
    price: 1200, stock: 200, weight: '600g',
    description: 'Safari White keeps whites brilliantly bright and colours vibrant. Superior cleaning formula made locally in Rwanda.',
    features: ['Whitening formula','Colour protection','Fresh scent','Made in Rwanda'],
    image: `${BASE}/2024/05/safari-white-ft.jpg`,
    images: [`${BASE}/2024/05/safari-white-ft.jpg`],
    tag: null,
  },
  {
    name: 'Tembo Laundry Soap 224g',
    brand: 'Tembo', category: 'Laundry Soap', subcategory: 'Bar Soap',
    price: 600, stock: 350, weight: '224g',
    description: 'Economy size Tembo laundry bar — strong cleaning power at an affordable price. Rwanda\'s value choice for everyday laundry.',
    features: ['Strong cleaning','Affordable','Long-lasting bar','Made in Rwanda'],
    image: `${BASE}/2024/05/tembo-ft-1.jpg`,
    images: [`${BASE}/2024/05/tembo-ft-1.jpg`],
    tag: 'value',
  },
  {
    name: 'Inyenyeri Laundry Soap 600g',
    brand: 'Inyenyeri', category: 'Laundry Soap', subcategory: 'Bar Soap',
    price: 1100, stock: 180, weight: '600g',
    description: 'Inyenyeri — "the star" — delivers star quality cleaning for all fabric types. Gentle enough for delicates, tough enough for work clothes.',
    features: ['Safe for all fabrics','Star formula','Pleasant fragrance','Made in Rwanda'],
    image: `${BASE}/2024/05/Inyenyeri-ft.jpg`,
    images: [`${BASE}/2024/05/Inyenyeri-ft.jpg`],
    tag: null,
  },
  {
    name: 'Sulfo Laundry Soap 500g',
    brand: 'Sulfo', category: 'Laundry Soap', subcategory: 'Bar Soap',
    price: 1000, stock: 300, weight: '500g',
    description: 'The original Sulfo laundry soap — 60+ years of quality cleaning excellence. A household name across Rwanda and East Africa.',
    features: ['Original formula since 1962','Tough on dirt','Gentle on hands','Made in Rwanda'],
    image: `${BASE}/2024/05/Sulfo-ft.jpg`,
    images: [`${BASE}/2024/05/Sulfo-ft.jpg`],
    tag: 'heritage',
  },
  {
    name: 'Magic Liquid Soap 5L',
    brand: 'Magic', category: 'Laundry Soap', subcategory: 'Liquid Detergent',
    price: 8500, stock: 120, weight: '5L',
    description: 'Magic Savon Liquide — powerful liquid laundry detergent for machine and hand washing. Cuts through grease and stains effortlessly.',
    features: ['Machine & hand wash','Grease cutting','Fresh scent','Bulk economy size'],
    image: `${BASE}/2024/05/Magic-ft.jpg`,
    images: [`${BASE}/2024/05/Magic-ft.jpg`],
    tag: 'family-size',
  },

  // ── TOILET / BEAUTY SOAP ───────────────────────────────────────
  {
    name: 'Claire Savon Toilet Soap 80g',
    brand: 'Claire', category: 'Toilet Soap', subcategory: 'Beauty Bar',
    price: 900, stock: 400, weight: '80g',
    description: 'Claire beauty soap gently cleanses and moisturises your skin. Enriched with a delicate fragrance that lasts through the day.',
    features: ['Moisturising formula','Delicate fragrance','Gentle on skin','Made in Rwanda'],
    image: `${BASE}/2024/05/Clair-soap-Large-ft.jpg`,
    images: [`${BASE}/2024/05/Clair-soap-Large-ft.jpg`, `${BASE}/2024/05/Clair-soap-small-ft.jpg`],
    tag: 'bestseller',
  },
  {
    name: 'Claire Savon Toilet Soap 30g',
    brand: 'Claire', category: 'Toilet Soap', subcategory: 'Beauty Bar',
    price: 400, stock: 500, weight: '30g',
    description: 'Travel size Claire soap — perfect for on the go freshness. Same great moisturising formula in a compact size.',
    features: ['Travel size','Moisturising','Fresh scent','Made in Rwanda'],
    image: `${BASE}/2024/05/Clair-soap-small-ft.jpg`,
    images: [`${BASE}/2024/05/Clair-soap-small-ft.jpg`],
    tag: null,
  },
  {
    name: 'Dawa Savon Antibacterial Soap 100g',
    brand: 'Dawa', category: 'Toilet Soap', subcategory: 'Antibacterial',
    price: 900, stock: 280, weight: '100g',
    description: 'Dawa Savon antibacterial soap protects your family from harmful germs. Hospital grade antibacterial action for everyday family hygiene.',
    features: ['Antibacterial protection','Kills 99.9% of germs','Gentle daily use','Family safe'],
    image: `${BASE}/2024/05/Dawa-ft.jpg`,
    images: [`${BASE}/2024/05/Dawa-ft.jpg`],
    tag: 'antibacterial',
  },
  {
    name: 'Santé Savon Soap 75g',
    brand: 'Santé', category: 'Toilet Soap', subcategory: 'Beauty Bar',
    price: 700, stock: 320, weight: '75g',
    description: 'Santé beauty bar — your daily health ritual. Gentle cleansing with a refreshing fragrance for the whole family.',
    features: ['Health focused formula','Refreshing fragrance','Family safe','Made in Rwanda'],
    image: `${BASE}/2024/05/Santesoap-ft.jpg`,
    images: [`${BASE}/2024/05/Santesoap-ft.jpg`],
    tag: null,
  },
  {
    name: 'Nina Savon Luxury Soap 250g',
    brand: 'Nina', category: 'Toilet Soap', subcategory: 'Luxury Bar',
    price: 2200, stock: 150, weight: '250g',
    description: 'Nina — luxury soap for the discerning woman. Extra large beauty bar with premium moisturisers for silky smooth skin every day.',
    features: ['Luxury formula','Extra moisturising','Premium fragrance','Generous 250g size'],
    image: `${BASE}/2024/05/NinaSoap-ft.jpg`,
    images: [`${BASE}/2024/05/NinaSoap-ft.jpg`],
    tag: 'premium',
  },

  // ── PETROLEUM JELLY ────────────────────────────────────────────
  {
    name: 'Claire Perfume Jelly 250g',
    brand: 'Claire', category: 'Petroleum Jelly', subcategory: 'Perfumed',
    price: 2500, stock: 200, weight: '250g',
    description: 'Claire Perfume Jelly — luxuriously scented petroleum jelly that deeply moisturises and leaves skin silky smooth with a lasting fragrance.',
    features: ['Deep moisturising','Lasting fragrance','Non greasy finish','All skin types'],
    image: `${BASE}/2024/05/Claire-Ft.jpg`,
    images: [`${BASE}/2024/05/Claire-Ft.jpg`],
    tag: 'bestseller',
  },
  {
    name: 'Santé Petroleum Jelly 250g',
    brand: 'Santé', category: 'Petroleum Jelly', subcategory: 'Classic',
    price: 1800, stock: 180, weight: '250g',
    description: 'Pure Santé petroleum jelly for skin protection, lip care, and minor wound healing. A household essential for every family.',
    features: ['Multi purpose use','Skin protection','Lip care','Trusted formula'],
    image: `${BASE}/2024/05/CherieJelly-Ft.jpg`,
    images: [`${BASE}/2024/05/CherieJelly-Ft.jpg`],
    tag: null,
  },
  {
    name: 'Santé Herbal Petroleum Jelly 100g',
    brand: 'Santé', category: 'Petroleum Jelly', subcategory: 'Herbal',
    price: 1200, stock: 150, weight: '100g',
    description: 'Santé Herbal Jelly infused with natural herbal extracts for enhanced skin care. Soothes, protects and nourishes dry skin naturally.',
    features: ['Natural herbal extracts','Soothing formula','Nourishing care','Compact size'],
    image: `${BASE}/2024/05/CherieJelly-Ft.jpg`,
    images: [`${BASE}/2024/05/CherieJelly-Ft.jpg`],
    tag: 'natural',
  },
  {
    name: 'Mama Bebe Petroleum Jelly 250g',
    brand: 'Mama Bebe', category: 'Petroleum Jelly', subcategory: 'Baby Care',
    price: 2000, stock: 220, weight: '250g',
    description: 'Specially formulated for babies\' delicate skin. Mama Bebe jelly creates a protective barrier against moisture and irritants.',
    features: ['Baby safe formula','Extra gentle','Hypoallergenic','Paediatrician tested'],
    image: `${BASE}/2024/05/Claire-Ft.jpg`,
    images: [`${BASE}/2024/05/Claire-Ft.jpg`],
    tag: 'baby',
  },
  {
    name: 'Malaika White Petroleum Jelly 200g',
    brand: 'Malaika', category: 'Petroleum Jelly', subcategory: 'Whitening',
    price: 1600, stock: 170, weight: '200g',
    description: 'Malaika White — skin lightening petroleum jelly with even skin tone properties. Brightens and moisturises for a radiant complexion.',
    features: ['Skin brightening','Even tone','Deep moisturising','Vitamin E enriched'],
    image: `${BASE}/2024/05/Claire-Ft.jpg`,
    images: [`${BASE}/2024/05/Claire-Ft.jpg`],
    tag: null,
  },
  {
    name: 'Chérie Petroleum Jelly 25g',
    brand: 'Chérie', category: 'Petroleum Jelly', subcategory: 'Mini',
    price: 500, stock: 400, weight: '25g',
    description: 'Chérie mini petroleum jelly — perfect pocket size for on the go lip and skin care. Fits in any bag or pocket.',
    features: ['Pocket size','Travel friendly','Multipurpose','Affordable'],
    image: `${BASE}/2024/05/CherieJelly-Ft.jpg`,
    images: [`${BASE}/2024/05/CherieJelly-Ft.jpg`],
    tag: null,
  },

  // ── BODY WASH ─────────────────────────────────────────────────
  {
    name: 'Vague Original Body Wash 500ml',
    brand: 'Vague', category: 'Body Wash', subcategory: 'Classic',
    price: 4500, stock: 160, weight: '500ml',
    description: 'Vague Original — the classic Sulfo body wash. Luxuriously creamy lather that cleanses and refreshes, leaving skin soft and fragrant.',
    features: ['Luxurious lather','Moisturising','All day freshness','Made in Rwanda'],
    image: `${BASE}/2024/02/vague-orange-6.jpg`,
    images: [`${BASE}/2024/02/vague-orange-6.jpg`],
    tag: 'bestseller',
  },
  {
    name: 'Vague Orange Body Wash 500ml',
    brand: 'Vague', category: 'Body Wash', subcategory: 'Fruity',
    price: 4500, stock: 140, weight: '500ml',
    description: 'Vague Orange — burst of citrus freshness every shower. Energising orange formula to kickstart your morning routine.',
    features: ['Citrus burst','Energising scent','Rich lather','Moisturising'],
    image: `${BASE}/2024/02/vague-orange-6.jpg`,
    images: [`${BASE}/2024/02/vague-orange-6.jpg`],
    tag: null,
  },
  {
    name: 'Vague Marine Body Wash 500ml',
    brand: 'Vague', category: 'Body Wash', subcategory: 'Marine',
    price: 4500, stock: 130, weight: '500ml',
    description: 'Vague Marine — ocean fresh sensation in every shower. Cool aquatic fragrance that revitalises and awakens your senses.',
    features: ['Ocean fresh scent','Cool & revitalising','Rich creamy lather','Skin softening'],
    image: `${BASE}/2024/02/vague-orange-6.jpg`,
    images: [`${BASE}/2024/02/vague-orange-6.jpg`],
    tag: null,
  },
  {
    name: 'Vague Herbal Body Wash 500ml',
    brand: 'Vague', category: 'Body Wash', subcategory: 'Herbal',
    price: 4500, stock: 120, weight: '500ml',
    description: 'Vague Herbal — natural herbal extracts for a gentle, nourishing cleanse. Perfect for sensitive skin types seeking a natural approach.',
    features: ['Natural herbal extracts','Sensitive skin safe','Gentle formula','Calming scent'],
    image: `${BASE}/2024/02/vague-orange-6.jpg`,
    images: [`${BASE}/2024/02/vague-orange-6.jpg`],
    tag: 'natural',
  },
  {
    name: 'Santé Antibacterial Body Wash 500ml',
    brand: 'Santé', category: 'Body Wash', subcategory: 'Antibacterial',
    price: 4800, stock: 200, weight: '500ml',
    description: 'Santé Antibacterial body wash gives your skin 12 hour protection from bacteria. Clinically proven formula for total body hygiene.',
    features: ['12 hour protection','Kills 99.9% bacteria','Daily use safe','Fresh clean scent'],
    image: `${BASE}/2024/02/vague-orange-6.jpg`,
    images: [`${BASE}/2024/02/vague-orange-6.jpg`],
    tag: 'antibacterial',
  },

  // ── LOTIONS & CREAMS ──────────────────────────────────────────
  {
    name: 'Claire Cocoa Butter Lotion 400ml',
    brand: 'Claire', category: 'Lotion & Cream', subcategory: 'Body Lotion',
    price: 5500, stock: 180, weight: '400ml',
    description: 'Claire Cocoa Butter body lotion deeply moisturises and leaves your skin glowing with a rich, chocolatey scent. 24 hour hydration.',
    features: ['24 hour hydration','Cocoa butter enriched','Glow enhancing','Non greasy'],
    image: `${BASE}/2024/05/Claire-Ft.jpg`,
    images: [`${BASE}/2024/05/Claire-Ft.jpg`],
    tag: 'bestseller',
  },
  {
    name: 'Claire Cocoa Butter Lotion 100ml',
    brand: 'Claire', category: 'Lotion & Cream', subcategory: 'Body Lotion',
    price: 1800, stock: 250, weight: '100ml',
    description: 'Travel size Claire Cocoa Butter lotion. Same premium formula in a handy size — perfect for handbags and travel.',
    features: ['Travel size','24 hour hydration','Rich cocoa scent','Non greasy'],
    image: `${BASE}/2024/05/Claire-Ft.jpg`,
    images: [`${BASE}/2024/05/Claire-Ft.jpg`],
    tag: null,
  },
  {
    name: 'Claire Body Milk Lotion 400ml',
    brand: 'Claire', category: 'Lotion & Cream', subcategory: 'Body Milk',
    price: 5200, stock: 160, weight: '400ml',
    description: 'Claire Body Milk — ultra light, fast absorbing body milk that leaves skin visibly soft and radiant. Perfect for daily use.',
    features: ['Ultra light texture','Fast absorbing','Visible radiance','Daily use'],
    image: `${BASE}/2024/05/Claire-Ft.jpg`,
    images: [`${BASE}/2024/05/Claire-Ft.jpg`],
    tag: null,
  },
  {
    name: 'Sousana Glycerine Cream 125g',
    brand: 'Sousana', category: 'Lotion & Cream', subcategory: 'Glycerine Cream',
    price: 2200, stock: 200, weight: '125g',
    description: 'Sousana Glycerine cream — intensive moisturising treatment enriched with pure glycerine. Heals dry, cracked skin overnight.',
    features: ['Intensive moisture','Pure glycerine','Heals dry skin','Overnight treatment'],
    image: `${BASE}/2024/05/Sousana-ft.jpg`,
    images: [`${BASE}/2024/05/Sousana-ft.jpg`],
    tag: null,
  },

  // ── HAIR CARE ─────────────────────────────────────────────────
  {
    name: 'Claire Shampoo 1L',
    brand: 'Claire', category: 'Hair Care', subcategory: 'Shampoo',
    price: 6500, stock: 120, weight: '1L',
    description: 'Claire Shampoo for strong, healthy, beautiful hair. Family size bottle for everyday cleansing that leaves hair soft, shiny and manageable.',
    features: ['For all hair types','Family size','Strengthening formula','Natural shine'],
    image: `${BASE}/2024/05/shampoo-ft.jpg`,
    images: [`${BASE}/2024/05/shampoo-ft.jpg`],
    tag: 'family-size',
  },
  {
    name: 'Super Curl Hair Gel 160g',
    brand: 'Super Curl', category: 'Hair Care', subcategory: 'Hair Gel',
    price: 2800, stock: 180, weight: '160g',
    description: 'Super Curl strong hold gel for defined curls and styles that last all day. Frizz control and moisture lock for beautiful curls.',
    features: ['Strong hold','Frizz control','Defined curls','No flaking'],
    image: `${BASE}/2024/05/supercurl-ft.jpg`,
    images: [`${BASE}/2024/05/supercurl-ft.jpg`],
    tag: 'bestseller',
  },
  {
    name: 'Super Curl Hair Gel 80g',
    brand: 'Super Curl', category: 'Hair Care', subcategory: 'Hair Gel',
    price: 1600, stock: 200, weight: '80g',
    description: 'Super Curl original hair gel in a convenient mid size. Same strong hold formula for defined styles at great value.',
    features: ['Strong hold','Defined styles','All day hold','Value size'],
    image: `${BASE}/2024/05/supercurl-ft.jpg`,
    images: [`${BASE}/2024/05/supercurl-ft.jpg`],
    tag: null,
  },
  {
    name: 'Black Pearl Hair Dye 6g',
    brand: 'Black Pearl', category: 'Hair Care', subcategory: 'Hair Dye',
    price: 800, stock: 300, weight: '6g',
    description: 'Black Pearl instant hair colour — rich, deep black that covers greys completely. Fast application with natural-looking results.',
    features: ['100% grey coverage','Instant colour','Long-lasting','Natural look'],
    image: `${BASE}/2024/05/LYS-ft.jpg`,
    images: [`${BASE}/2024/05/LYS-ft.jpg`],
    tag: 'bestseller',
  },
  {
    name: 'Vague Talcum Powder',
    brand: 'Vague', category: 'Hair Care', subcategory: 'Talcum Powder',
    price: 1500, stock: 220, weight: '200g',
    description: 'Vague Talc — fine, smooth talcum powder that keeps you fresh and comfortable all day. Gentle enough for the whole family.',
    features: ['Ultra fine powder','All day freshness','Family safe','Vague fragrance'],
    image: `${BASE}/2024/05/Talcum-ft.jpg`,
    images: [`${BASE}/2024/05/Talcum-ft.jpg`],
    tag: null,
  },

  // ── HAND CARE & SANITISERS ────────────────────────────────────
  {
    name: 'Santé Hand Sanitizer 500ml',
    brand: 'Santé', category: 'Hand & Hygiene', subcategory: 'Sanitizer',
    price: 4500, stock: 200, weight: '500ml',
    description: 'Santé Hand Sanitizer with 70% alcohol content — kills 99.99% of germs in seconds. Essential hygiene for home, office and travel.',
    features: ['70% alcohol','Kills 99.99% germs','Quick dry formula','With moisturisers'],
    image: `${BASE}/2024/05/Santesoap-ft.jpg`,
    images: [`${BASE}/2024/05/Santesoap-ft.jpg`],
    tag: 'essential',
  },
  {
    name: 'Santé Hand Sanitizer 120ml',
    brand: 'Santé', category: 'Hand & Hygiene', subcategory: 'Sanitizer',
    price: 1500, stock: 300, weight: '120ml',
    description: 'Handy pocket size Santé sanitizer. Keep it in your bag, car or desk for on the go germ protection wherever you go.',
    features: ['Pocket size','70% alcohol','On the go','Quick dry'],
    image: `${BASE}/2024/05/Santesoap-ft.jpg`,
    images: [`${BASE}/2024/05/Santesoap-ft.jpg`],
    tag: null,
  },
  {
    name: 'K-Star Hand Rub 1L',
    brand: 'K-Star', category: 'Hand & Hygiene', subcategory: 'Medical Grade',
    price: 8000, stock: 100, weight: '1L',
    description: 'K-Star medical grade hand rub — WHO formulated disinfectant for hospitals, clinics, and high-risk environments.',
    features: ['WHO formula','Medical grade','Hospital safe','Clinic tested'],
    image: `${BASE}/2024/05/Santesoap-ft.jpg`,
    images: [`${BASE}/2024/05/Santesoap-ft.jpg`],
    tag: 'medical',
  },

  // ── HOUSEHOLD CLEANING ────────────────────────────────────────
  {
    name: 'Spot Scouring Powder 500g',
    brand: 'Spot', category: 'Household Cleaning', subcategory: 'Scouring',
    price: 1000, stock: 280, weight: '500g',
    description: 'Spot Scouring Powder — powerful abrasive cleaning for stubborn stains on pots, sinks, tiles and bathroom surfaces.',
    features: ['Deep clean','Non scratch formula','Whitening effect','Multi surface'],
    image: `${BASE}/2024/05/Sulfo-ft.jpg`,
    images: [`${BASE}/2024/05/Sulfo-ft.jpg`],
    tag: null,
  },
  {
    name: 'Rub Bleach 500ml',
    brand: 'Rub', category: 'Household Cleaning', subcategory: 'Bleach',
    price: 1500, stock: 220, weight: '500ml',
    description: 'Rub Bleach — powerful disinfecting bleach for laundry whitening, bathroom cleaning and surface disinfection.',
    features: ['Disinfects & whitens','Surface cleaning','Germ killing','Value pack'],
    image: `${BASE}/2024/05/Sulfo-ft.jpg`,
    images: [`${BASE}/2024/05/Sulfo-ft.jpg`],
    tag: null,
  },
  {
    name: 'Beatall All Purpose Cleaner 1L',
    brand: 'Beatall', category: 'Household Cleaning', subcategory: 'Multi-purpose',
    price: 3500, stock: 150, weight: '1L',
    description: 'Beatall cleans everything — floors, surfaces, appliances and more. One bottle for the whole house with a fresh citrus scent.',
    features: ['Multi surface','Citrus fresh scent','Streak free','Concentrated formula'],
    image: `${BASE}/2024/05/Magic-ft.jpg`,
    images: [`${BASE}/2024/05/Magic-ft.jpg`],
    tag: null,
  },
  {
    name: 'Diamond Vinegar 750ml',
    brand: 'Diamond', category: 'Household Cleaning', subcategory: 'Natural Cleaner',
    price: 2000, stock: 180, weight: '750ml',
    description: 'Diamond White Vinegar — natural cleaning agent for eco friendly households. Perfect for descaling, glass cleaning and natural disinfection.',
    features: ['Natural formula','Eco friendly','Descaling','Multi purpose'],
    image: `${BASE}/2024/05/Magic-ft.jpg`,
    images: [`${BASE}/2024/05/Magic-ft.jpg`],
    tag: 'eco',
  },

  // ── NIL DRINKING WATER ────────────────────────────────────────
  {
    name: 'NIL Drinking Water 1.5L',
    brand: 'NIL', category: 'Drinking Water', subcategory: 'Still Water',
    price: 700, stock: 500, weight: '1.5L',
    description: 'NIL Source du Nil — pure natural spring water from the heart of Rwanda. ISO 22000 certified food safety. Crisp, clean, refreshing.',
    features: ['ISO 22000 certified','Natural spring water','Pure & crisp','Perfect hydration'],
    image: `${BASE}/2024/01/about-us-1.jpg`,
    images: [`${BASE}/2024/01/about-us-1.jpg`],
    tag: 'bestseller',
  },
  {
    name: 'NIL Drinking Water 0.5L',
    brand: 'NIL', category: 'Drinking Water', subcategory: 'Still Water',
    price: 400, stock: 600, weight: '0.5L',
    description: 'NIL 500ml — the perfect on the go companion. Pure Rwandan spring water in a handy portable bottle. ISO 22000 certified.',
    features: ['Portable size','Pure spring water','ISO certified','Refreshing'],
    image: `${BASE}/2024/01/about-us-1.jpg`,
    images: [`${BASE}/2024/01/about-us-1.jpg`],
    tag: null,
  },
  {
    name: 'NIL Drinking Water 5L',
    brand: 'NIL', category: 'Drinking Water', subcategory: 'Still Water',
    price: 2200, stock: 300, weight: '5L',
    description: 'NIL 5L family water pack — keep your family hydrated with pure Rwandan spring water. Great value for everyday drinking.',
    features: ['Family size','Pure spring water','Great value','ISO 22000 certified'],
    image: `${BASE}/2024/01/about-us-1.jpg`,
    images: [`${BASE}/2024/01/about-us-1.jpg`],
    tag: 'family-size',
  },
  {
    name: 'NIL Drinking Water 18.9L',
    brand: 'NIL', category: 'Drinking Water', subcategory: 'Office Dispenser',
    price: 7500, stock: 150, weight: '18.9L',
    description: 'NIL 18.9L office and home dispenser bottle. Perfect for water dispensers in offices, restaurants and homes. Bulk economy value.',
    features: ['Dispenser compatible','Office & home','Bulk economy','Pure spring water'],
    image: `${BASE}/2024/01/about-us-1.jpg`,
    images: [`${BASE}/2024/01/about-us-1.jpg`],
    tag: 'bulk',
  },

  // ── GLYCERINE ─────────────────────────────────────────────────
  {
    name: 'Sulfo Pure Glycerin 50ml',
    brand: 'Sulfo', category: 'Glycerine', subcategory: 'Pure Glycerine',
    price: 1200, stock: 200, weight: '50ml',
    description: 'USP grade pure glycerine — pharmaceutical quality for skin care, wound healing and home beauty treatments.',
    features: ['USP pharmaceutical grade','100% pure','Multi use','Skin healing'],
    image: `${BASE}/2024/05/Sousana-ft.jpg`,
    images: [`${BASE}/2024/05/Sousana-ft.jpg`],
    tag: null,
  },
  {
    name: 'Chérie Glycerine 50ml',
    brand: 'Chérie', category: 'Glycerine', subcategory: 'Scented Glycerine',
    price: 900, stock: 250, weight: '50ml',
    description: 'Chérie lightly scented glycerine with a delicate floral note. Excellent skin moisturiser and softener for daily beauty routines.',
    features: ['Lightly scented','Deep moisturising','Skin softening','Daily use'],
    image: `${BASE}/2024/05/Sousana-ft.jpg`,
    images: [`${BASE}/2024/05/Sousana-ft.jpg`],
    tag: null,
  },
];

export const CATEGORIES = [
  { name: 'Laundry Soap',      icon: '🧺', description: 'Powerful laundry bars & liquid detergents' },
  { name: 'Toilet Soap',       icon: '🧼', description: 'Premium beauty & antibacterial soaps' },
  { name: 'Petroleum Jelly',   icon: '✨', description: 'Moisturising jellies for skin & baby care' },
  { name: 'Body Wash',         icon: '🚿', description: 'Luxurious shower gels & body washes' },
  { name: 'Lotion & Cream',    icon: '💧', description: 'Nourishing body lotions & skin creams' },
  { name: 'Hair Care',         icon: '💇', description: 'Shampoos, gels, dyes & hair treatments' },
  { name: 'Hand & Hygiene',    icon: '🙌', description: 'Sanitizers & medical grade hand care' },
  { name: 'Household Cleaning',icon: '🏠', description: 'Powerful cleaners for a spotless home' },
  { name: 'Drinking Water',    icon: '💧', description: 'ISO 22000 certified pure spring water' },
  { name: 'Glycerine',         icon: '🌿', description: 'Pure & scented pharmaceutical glycerine' },
];

export const BRANDS = ['Claire','Santé','Vague','NIL','Tembo','Safari','Malaika','Super Curl','Black Pearl','Mama Bebe','Sousana','Chérie','K-Star','Sulfo','Diamond','Magic','Beatall','Rub','Spot','Dawa','Nina','Inyenyeri'];
